export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          phone: string;
          first_name: string;
          last_name: string;
          date_of_birth: string;
          address: string;
          city: string;
          state: string;
          country: string;
          postal_code: string;
          kyc_status: 'pending' | 'verified' | 'rejected';
          kyc_documents: any[];
          is_active: boolean;
          is_verified: boolean;
          role: 'user' | 'group_admin' | 'admin' | 'super_admin';
          created_at: string;
          updated_at: string;
          last_login: string | null;
          two_factor_enabled: boolean;
          two_factor_secret: string | null;
          profile_image_url: string | null;
          preferences: any;
        };
        Insert: {
          id?: string;
          email: string;
          phone: string;
          first_name: string;
          last_name: string;
          date_of_birth: string;
          address: string;
          city: string;
          state: string;
          country: string;
          postal_code: string;
          kyc_status?: 'pending' | 'verified' | 'rejected';
          kyc_documents?: any[];
          is_active?: boolean;
          is_verified?: boolean;
          role?: 'user' | 'group_admin' | 'admin' | 'super_admin';
          created_at?: string;
          updated_at?: string;
          last_login?: string | null;
          two_factor_enabled?: boolean;
          two_factor_secret?: string | null;
          profile_image_url?: string | null;
          preferences?: any;
        };
        Update: {
          id?: string;
          email?: string;
          phone?: string;
          first_name?: string;
          last_name?: string;
          date_of_birth?: string;
          address?: string;
          city?: string;
          state?: string;
          country?: string;
          postal_code?: string;
          kyc_status?: 'pending' | 'verified' | 'rejected';
          kyc_documents?: any[];
          is_active?: boolean;
          is_verified?: boolean;
          role?: 'user' | 'group_admin' | 'admin' | 'super_admin';
          created_at?: string;
          updated_at?: string;
          last_login?: string | null;
          two_factor_enabled?: boolean;
          two_factor_secret?: string | null;
          profile_image_url?: string | null;
          preferences?: any;
        };
      };
      groups: {
        Row: {
          id: string;
          name: string;
          description: string;
          group_type: 'community' | 'formal' | 'corporate';
          admin_id: string;
          is_active: boolean;
          settings: any;
          commission_rate: number;
          created_at: string;
          updated_at: string;
          max_members: number;
          current_members: number;
          group_code: string;
          invite_code: string;
          privacy_settings: any;
        };
        Insert: {
          id?: string;
          name: string;
          description: string;
          group_type: 'community' | 'formal' | 'corporate';
          admin_id: string;
          is_active?: boolean;
          settings?: any;
          commission_rate?: number;
          created_at?: string;
          updated_at?: string;
          max_members?: number;
          current_members?: number;
          group_code?: string;
          invite_code?: string;
          privacy_settings?: any;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string;
          group_type?: 'community' | 'formal' | 'corporate';
          admin_id?: string;
          is_active?: boolean;
          settings?: any;
          commission_rate?: number;
          created_at?: string;
          updated_at?: string;
          max_members?: number;
          current_members?: number;
          group_code?: string;
          invite_code?: string;
          privacy_settings?: any;
        };
      };
      group_members: {
        Row: {
          id: string;
          group_id: string;
          user_id: string;
          role: 'member' | 'moderator' | 'admin';
          status: 'pending' | 'active' | 'suspended' | 'removed';
          joined_at: string;
          permissions: any;
          commission_earned: number;
          total_contributions: number;
          total_savings: number;
        };
        Insert: {
          id?: string;
          group_id: string;
          user_id: string;
          role?: 'member' | 'moderator' | 'admin';
          status?: 'pending' | 'active' | 'suspended' | 'removed';
          joined_at?: string;
          permissions?: any;
          commission_earned?: number;
          total_contributions?: number;
          total_savings?: number;
        };
        Update: {
          id?: string;
          group_id?: string;
          user_id?: string;
          role?: 'member' | 'moderator' | 'admin';
          status?: 'pending' | 'active' | 'suspended' | 'removed';
          joined_at?: string;
          permissions?: any;
          commission_earned?: number;
          total_contributions?: number;
          total_savings?: number;
        };
      };
      savings_products: {
        Row: {
          id: string;
          group_id: string;
          name: string;
          type: 'target_savings' | 'fixed_savings' | 'turn_by_turn';
          target_amount: number;
          current_amount: number;
          interest_rate: number;
          duration_months: number;
          start_date: string;
          end_date: string;
          is_active: boolean;
          settings: any;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          group_id: string;
          name: string;
          type: 'target_savings' | 'fixed_savings' | 'turn_by_turn';
          target_amount: number;
          current_amount?: number;
          interest_rate: number;
          duration_months: number;
          start_date: string;
          end_date: string;
          is_active?: boolean;
          settings?: any;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          group_id?: string;
          name?: string;
          type?: 'target_savings' | 'fixed_savings' | 'turn_by_turn';
          target_amount?: number;
          current_amount?: number;
          interest_rate?: number;
          duration_months?: number;
          start_date?: string;
          end_date?: string;
          is_active?: boolean;
          settings?: any;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      contributions: {
        Row: {
          id: string;
          user_id: string;
          group_id: string;
          savings_product_id: string;
          amount: number;
          contribution_type: 'manual' | 'scheduled' | 'turn_by_turn';
          payment_method: 'bank_transfer' | 'card' | 'ussd' | 'wallet';
          status: 'pending' | 'completed' | 'failed' | 'cancelled';
          transaction_reference: string;
          payment_reference: string;
          commission_earned: number;
          created_at: string;
          updated_at: string;
          due_date: string | null;
          paid_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          group_id: string;
          savings_product_id: string;
          amount: number;
          contribution_type: 'manual' | 'scheduled' | 'turn_by_turn';
          payment_method: 'bank_transfer' | 'card' | 'ussd' | 'wallet';
          status?: 'pending' | 'completed' | 'failed' | 'cancelled';
          transaction_reference?: string;
          payment_reference?: string;
          commission_earned?: number;
          created_at?: string;
          updated_at?: string;
          due_date?: string | null;
          paid_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          group_id?: string;
          savings_product_id?: string;
          amount?: number;
          contribution_type?: 'manual' | 'scheduled' | 'turn_by_turn';
          payment_method?: 'bank_transfer' | 'card' | 'ussd' | 'wallet';
          status?: 'pending' | 'completed' | 'failed' | 'cancelled';
          transaction_reference?: string;
          payment_reference?: string;
          commission_earned?: number;
          created_at?: string;
          updated_at?: string;
          due_date?: string | null;
          paid_at?: string | null;
        };
      };
      loans: {
        Row: {
          id: string;
          user_id: string;
          group_id: string;
          amount: number;
          interest_rate: number;
          duration_months: number;
          status: 'pending' | 'approved' | 'disbursed' | 'active' | 'completed' | 'defaulted';
          purpose: string;
          collateral: any;
          guarantors: any[];
          repayment_schedule: any[];
          disbursed_amount: number;
          outstanding_balance: number;
          created_at: string;
          updated_at: string;
          approved_by: string | null;
          approved_at: string | null;
          disbursed_at: string | null;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          group_id: string;
          amount: number;
          interest_rate: number;
          duration_months: number;
          status?: 'pending' | 'approved' | 'disbursed' | 'active' | 'completed' | 'defaulted';
          purpose: string;
          collateral?: any;
          guarantors?: any[];
          repayment_schedule?: any[];
          disbursed_amount?: number;
          outstanding_balance?: number;
          created_at?: string;
          updated_at?: string;
          approved_by?: string | null;
          approved_at?: string | null;
          disbursed_at?: string | null;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          group_id?: string;
          amount?: number;
          interest_rate?: number;
          duration_months?: number;
          status?: 'pending' | 'approved' | 'disbursed' | 'active' | 'completed' | 'defaulted';
          purpose?: string;
          collateral?: any;
          guarantors?: any[];
          repayment_schedule?: any[];
          disbursed_amount?: number;
          outstanding_balance?: number;
          created_at?: string;
          updated_at?: string;
          approved_by?: string | null;
          approved_at?: string | null;
          disbursed_at?: string | null;
          completed_at?: string | null;
        };
      };
      loan_repayments: {
        Row: {
          id: string;
          loan_id: string;
          user_id: string;
          amount: number;
          principal_amount: number;
          interest_amount: number;
          payment_method: 'bank_transfer' | 'card' | 'ussd' | 'wallet';
          status: 'pending' | 'completed' | 'failed';
          transaction_reference: string;
          payment_reference: string;
          due_date: string;
          paid_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          loan_id: string;
          user_id: string;
          amount: number;
          principal_amount: number;
          interest_amount: number;
          payment_method: 'bank_transfer' | 'card' | 'ussd' | 'wallet';
          status?: 'pending' | 'completed' | 'failed';
          transaction_reference?: string;
          payment_reference?: string;
          due_date: string;
          paid_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          loan_id?: string;
          user_id?: string;
          amount?: number;
          principal_amount?: number;
          interest_amount?: number;
          payment_method?: 'bank_transfer' | 'card' | 'ussd' | 'wallet';
          status?: 'pending' | 'completed' | 'failed';
          transaction_reference?: string;
          payment_reference?: string;
          due_date?: string;
          paid_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      escrow_transactions: {
        Row: {
          id: string;
          buyer_id: string;
          seller_id: string;
          group_id: string;
          amount: number;
          description: string;
          status: 'pending' | 'funded' | 'disputed' | 'released' | 'cancelled';
          payment_method: 'bank_transfer' | 'card' | 'ussd' | 'wallet';
          transaction_reference: string;
          payment_reference: string;
          dispute_reason: string | null;
          released_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          buyer_id: string;
          seller_id: string;
          group_id: string;
          amount: number;
          description: string;
          status?: 'pending' | 'funded' | 'disputed' | 'released' | 'cancelled';
          payment_method: 'bank_transfer' | 'card' | 'ussd' | 'wallet';
          transaction_reference?: string;
          payment_reference?: string;
          dispute_reason?: string | null;
          released_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          buyer_id?: string;
          seller_id?: string;
          group_id?: string;
          amount?: number;
          description?: string;
          status?: 'pending' | 'funded' | 'disputed' | 'released' | 'cancelled';
          payment_method?: 'bank_transfer' | 'card' | 'ussd' | 'wallet';
          transaction_reference?: string;
          payment_reference?: string;
          dispute_reason?: string | null;
          released_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      complaints: {
        Row: {
          id: string;
          user_id: string;
          group_id: string;
          type: 'transaction' | 'service' | 'technical' | 'dispute' | 'other';
          category: string;
          title: string;
          description: string;
          status: 'open' | 'in_progress' | 'resolved' | 'closed';
          priority: 'low' | 'medium' | 'high' | 'urgent';
          assigned_to: string | null;
          resolution: string | null;
          created_at: string;
          updated_at: string;
          resolved_at: string | null;
          attachments: any[];
        };
        Insert: {
          id?: string;
          user_id: string;
          group_id: string;
          type: 'transaction' | 'service' | 'technical' | 'dispute' | 'other';
          category: string;
          title: string;
          description: string;
          status?: 'open' | 'in_progress' | 'resolved' | 'closed';
          priority?: 'low' | 'medium' | 'high' | 'urgent';
          assigned_to?: string | null;
          resolution?: string | null;
          created_at?: string;
          updated_at?: string;
          resolved_at?: string | null;
          attachments?: any[];
        };
        Update: {
          id?: string;
          user_id?: string;
          group_id?: string;
          type?: 'transaction' | 'service' | 'technical' | 'dispute' | 'other';
          category?: string;
          title?: string;
          description?: string;
          status?: 'open' | 'in_progress' | 'resolved' | 'closed';
          priority?: 'low' | 'medium' | 'high' | 'urgent';
          assigned_to?: string | null;
          resolution?: string | null;
          created_at?: string;
          updated_at?: string;
          resolved_at?: string | null;
          attachments?: any[];
        };
      };
      system_configurations: {
        Row: {
          id: string;
          key: string;
          value: any;
          type: 'string' | 'number' | 'boolean' | 'object';
          description: string;
          is_public: boolean;
          updated_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          value: any;
          type: 'string' | 'number' | 'boolean' | 'object';
          description: string;
          is_public?: boolean;
          updated_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          value?: any;
          type?: 'string' | 'number' | 'boolean' | 'object';
          description?: string;
          is_public?: boolean;
          updated_by?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      commission_rates: {
        Row: {
          id: string;
          service_type: 'savings' | 'loans' | 'contributions' | 'escrow' | 'general';
          rate_percentage: number;
          minimum_amount: number;
          maximum_amount: number | null;
          group_id: string | null;
          is_active: boolean;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          service_type: 'savings' | 'loans' | 'contributions' | 'escrow' | 'general';
          rate_percentage: number;
          minimum_amount?: number;
          maximum_amount?: number | null;
          group_id?: string | null;
          is_active?: boolean;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          service_type?: 'savings' | 'loans' | 'contributions' | 'escrow' | 'general';
          rate_percentage?: number;
          minimum_amount?: number;
          maximum_amount?: number | null;
          group_id?: string | null;
          is_active?: boolean;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          message: string;
          type: 'info' | 'success' | 'warning' | 'error';
          channel: 'email' | 'sms' | 'push' | 'in_app';
          status: 'pending' | 'sent' | 'delivered' | 'failed';
          metadata: any;
          sent_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          message: string;
          type?: 'info' | 'success' | 'warning' | 'error';
          channel: 'email' | 'sms' | 'push' | 'in_app';
          status?: 'pending' | 'sent' | 'delivered' | 'failed';
          metadata?: any;
          sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          message?: string;
          type?: 'info' | 'success' | 'warning' | 'error';
          channel?: 'email' | 'sms' | 'push' | 'in_app';
          status?: 'pending' | 'sent' | 'delivered' | 'failed';
          metadata?: any;
          sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          user_id: string | null;
          action: string;
          resource_type: string;
          resource_id: string;
          old_values: any;
          new_values: any;
          ip_address: string;
          user_agent: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          action: string;
          resource_type: string;
          resource_id: string;
          old_values?: any;
          new_values?: any;
          ip_address: string;
          user_agent: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          action?: string;
          resource_type?: string;
          resource_id?: string;
          old_values?: any;
          new_values?: any;
          ip_address?: string;
          user_agent?: string;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
